name:                winasyncsocket
version:             0.1.0.0
github:              "githubuser/winasyncsocket"
license:             BSD-3-Clause
author:              "axionbuster"
maintainer:          "axionbuster@gmail.com"
copyright:           "2025 axionbuster"

language: GHC2021

default-extensions:
- BlockArguments
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- CApiFFI
- CPP
- LambdaCase
- OverloadedRecordDot
- PatternSynonyms
- RecordWildCards
- ViewPatterns

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

synopsis:            Windows Asynchronous Socket Programming in Haskell
category:            Network, System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/winasyncsocket#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.12.1 && < 0.13
- Win32 >= 2.13.4 && < 2.14

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  c-sources:
  - src/ax.c
  include-dirs: src
  build-tools: hsc2hs

executables:
  winasyncsocket-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=--io-manager=native
    dependencies:
    - winasyncsocket
